### ISSUE TITLE
Disappearing toolbar

### ISSUE THREAD

**Issue by legovini** [mapsme/omim#4374]
With the upgrade that came out today the bottom toolbar often disappears and there is no way to interact with the app. This happens for example when cancelling a routing operation. This didn't happen with the previous version. (Nexus 6, stock Android N.)

**Comment by Norbert80** [comment]
I experience the same problem.

**Comment by burivuh** [comment]
Fixed in 6.4.3

**Comment by Norbert80** [comment]
@legovini I experience this issue again with build "6.4.3-Google". So it seems to be not fully covered by your fix.

**Comment by legovini** [comment]
@Norbert80 the fix was not mine, anyway I can't reproduce the problem with 6.4.3-Google.

**Comment by Norbert80** [comment]
It still happens sporadically. Before the fix it happend more often and reproducible.

**Comment by Norbert80** [comment]
My report of experiencing this bug seems to be a duplicate of #4434.
